### ISSUE TITLE
Research on Volume Rendering of DICOM

### ISSUE THREAD

**Issue by fayeli** [fayeli/biojs-vis-bonestagram#15]
DICOM images usually come in a set of ~100+ image file in .dcm format. Since they are cross sections across the body, we cannot directly overlay a single DICOM image in Bonestagram. I'm researching into the technique of volume rendering, which renders multiple cross section images into a 3D model. In the browser, there is a component from x3dom that seem to be great for this purpose:
http://www.x3dom.org/volumerendering/

Documentation: http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/volume.html

Examples:
http://examples.x3dom.org/volren/volrenOpacityTestTF_aorta.xhtml
http://examples.x3dom.org/volren/volrenMPR_aorta.xhtml

**Comment by fayeli** [comment]
Resources:
http://www.web3d.org/sites/default/files/presentations/X3D%20WebGL%20based%20Volume%20Rendering/med_X3D-WebGL-Volume-Rendering_kabongo.pdf
http://www.web3d.org/sites/default/files/presentations/Visualization%3B%20Brain%20Imaging%3B%20Surgical%20Training/Health-Medical.pdf
http://doc.x3dom.org/tutorials/applicationTutorials/simpleAR/index.html

**Comment by fayeli** [comment]
### How to create volume rendering of DICOM on the web

I couldn't seem to find very clear usage instruction of x3dom volume rendering, so, I thought I'd summarize what I figured out about volume rendering of DICOM in this short guide.
1. Compose an Image Texture Atlas from DICOM images
   DICOM images are binary data that aren't great for loading on the web. They also comes in a folder of many files, making the loading and conversion of DICOM not ideal to be done on the browser in Javascript.
   The solution here is that we would preprocess the DICOM images so that they become web compatible. Using the given script (https://raw.githubusercontent.com/VolumeRC/AtlasConversionScripts/master/src/convertDICOM.py), we can turn a folder of DICOM images into a single composed mosaic image in PNG format. The result, a image texture atlas, contains all the slices in rows and columns.
2. Load x3dom
   We'll need to load the full version of x3dom and its css to support the volume rendering component. e.g.

```
 <script src="x3dom-full.js"></script>
 <link rel="stylesheet" href="x3dom.css">
```
1. Create Volume Rendering with Markup
   The x3dom volume rendering component takes the image texture atlas and generates visualisation on the web. To do so, we just need to specify the url to the image texture atlas and use the markup language of x3dom in the HTML file. e.g.

`
 <X3D xmlns='http://www.web3d.org/specifications/x3d-namespace'
         showStat='true' showLog='false' width='500px' height='500px'>
<Scene>
<Background skyColor='0.0 0.0 0.0'/>
<Viewpoint description='Default' zNear='0.0001' zFar='100'/>
<Transform>
<VolumeData id='volume' dimensions='4.0 4.0 4.0'>
              <ImageTextureAtlas containerField='voxels' url='aorta4096.png'
                                 numberOfSlices='96' slicesOverX='10' slicesOverY='10'/>
              <OpacityMapVolumeStyle lightFactor='1.2' opacityFactor='6.0'>
                <ImageTexture containerField='transferFunction' url='transfer.png'/>
              </OpacityMapVolumeStyle>
            </VolumeData>
          </Transform>
      </Scene>
    </X3D>
`

The resources for this were all kinda all over the place, so it took a while to learn about how it works. I think this is all it's needed for the volume rendering visualisation, but I'll try this out tomorrow and confirm! (:

**Comment by sacdallago** [comment]
Point 1 is a pre-processing step. In order not to add a backend to the solution that you propose, I would consider this processing step to be performed by the users on their computer. Otherwise we incur in the so-problematic privacy issues that we have been trying to avoid up until now.
This immediately brings me to the next point: this a bit of an overhead for a user. I would consider this feature a nice-to-have, but not top priority for the final project :)

Nice! So X3D is similar, in some sense, to SVG elements; that is: it is an extension to the native HTML markup language to perform special tasks.
Specifically with SVG you can create lines and point elements, and these are used to generate scalable vector graphics (SVG) that render on your browser. I guess the concept (by reading the code you posted above) of x3dom is similar. Adding JavaScript functionalities will later allow you to add some behavior to your representation. Let me explain:
What this framework allows you to do is define a region in you HTML code where some new tags (like `VolmueData`) are rendered. From what I read, conceptually you can imagine that you define a "room" and then you put in different objects. Objects in real life are just polygons in space, which again become volumes, from where I infer that `VolumeData` is a such volume in space.
Later you have to imagine that you just defined a room and some volumes in it, but it lacks a logic (for example: does this room have "gravity"? Should something happen if an object is dragged with the mouse from one part to the other of the room? etc.).

I believe that writing all of this code, like above, in HTML isn't really what you want to go for. There definitely has to be a tool to dynamically manage the HTML via JavaScript functions, so that you can set the view parameters or add data to the visualization via JS.
Maybe the specification is too young though (I read that the idea started in 2012).

Very interesting anyway :) appreciate that you looked into this :)

**Comment by fayeli** [comment]
Yeah, Damon did mention that the x3dom specs are a bit outdated and it might not be the best suited if we are planning on manipulating the visualisation with Javascript. I can already imagine that it might be a headache to move the volume rendering around based on user face movement on Web cam.

However, I also look into volume rendering on the web besides x3dom!
http://lebarbacom.ipage.com/blog/
This page here talks about creating volume rendering with three.js and webgl, which would mean all implementations are in js! (:

Although it is still true that there is the same preprocessing needed... DICOM isn'T very web compatible unfortunately D: 

But I still think that a visualisation that's generated from DICOM files would make Bonestagram more fitting to the biological data visualisation focus of BioJS.

Should I spend time trying volume rendering still?

**Comment by sacdallago** [comment]
Hi @fayeli ,
sorry for getting back this late, I only get email notifications if you @ mention me :D Just saw this going over the issues here :)

I suggest you to spend more energy on other aspects, such as for example testing the actual state with different images that the ones used for testing, or again redefine the layout, or implement the social aspects, aso.

As a side note: I bought the [bonestagram.com](http://bonestagram.com) domain ;) it's redirecting to the firebase app for now. It might be nice if you could look into some (even free, as there is no need for a backend) hosting solution or so :)

**Comment by fayeli** [comment]
That's awesome! @sacdallago Really love that it's exactly bonestagram.com! I'll look into hosting in a bit.. there's a chance that firebase hosting will let us add custom domain. Will keep you posted! (: 

But yeah, last week I spent a lot of time on trying volume rendering and it didn't get very far. I agree with you that it's more worth my time on other aspects for now. 

I'm gonna close this issue and move on to UI.. the fun part ((:

**Comment by sacdallago** [comment]
Btw I am already loving the redesign! :) Veeeery minimal

I'm happy to see that you got way more taste than I do! :D I'm trying really hard to design good UIs but I guess I was just not born to do so (eg. http://cell.dallago.us/search ) 😢
