### ISSUE TITLE
Interfaces in JavaScript

### ISSUE THREAD

**Issue by sacdallago** [fayeli/biojs-vis-bonestagram#16]
I thought about the problem again, and actually what I came up with is a little bit different from what I said before and should not be that hard. The idea here is the following:
1. You have certain return values and input parameters for the different parts of your code, eg: the video stream you obtain by calling `.getVideoStream()`, you get another video stream with the overlay of two different streams by using `.joinStreams(videoStream1, videoStream2)`
2. You make these functions as _independent as possible_
3. Somewhere you put it all together, in a fashion that if someone wants to change or expand your code, she/he can easily do so.

I think the 2nd point here is the most important one with respect to being able to expand the functionality.
I think in terms of what your code looks now, what you would need to do is to incapsulate all of the variables and calculations inside the scope of the function.
An example: https://github.com/fayeli/Bonestagram/blob/master/modular/js/app/bonestagram.js#L87
Here the variables `vid` `height` `width` aso are taken directly from the context. Since I assume, though, that this is a specific case of the face and the overlay of the dental images, I would rather write this function so that it is completely unaware of the context and could be taken as a model for further implementations.
You could, for instance, pass a variable (or several) to `drawFaceLoop` in order for it to do what it is supposed to do.

Hope this makes sense, else just ask here :)

**Comment by fayeli** [comment]
Hi @sacdallago! Sorry I saw this a bit late into the week, I've been working on the screen shot feature. 

But yeah, that definitely makes sense to encapsulate and make function as independent as possible. For the width and height variables, I am grabbing the width and height of the user video stream at initialisation (https://github.com/fayeli/Bonestagram/blob/master/modular/js/app/bonestagram.js#L186). They don't depend on the face overlay or the dental image. Reason I had them as global private variables, amongst a bunch of others variables(https://github.com/fayeli/Bonestagram/blob/master/modular/js/app/bonestagram.js#L4), is so that their scope would reach all the further computation that requires them. Width and height, and other position variables are quite the essentials for our image processing, whether its the clm algorithm or the optical flow algorithm (i.e. drawFaceLoop and drawHandLoop)

I think I really need some work on the documentation, especially on this confusing architecture haha. Basically, there is only one video stream running at all times. It is the video element with class="bonestagram_video". Overlays get drawn to separate HTML canvas element, which is a layer on top of the video.

Does this sound like the kind of independent functions you have in mind?
