### ISSUE TITLE
Make bonestagram modular (upload to biojs)

### ISSUE THREAD

**Issue by sacdallago** [fayeli/biojs-vis-bonestagram#8]
Ideally, the flow of using this component would be similar to this: http://leafletjs.com/

In the above example you do the following:
- Import the JS component (and styles, if needed)

``` HTML
<html>
  <head>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css">
    <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
  </head>
  <body>
  </body>
</html>
```
- Initialize the component:

``` javascript
var map = L.map('myDiv').setView([51.505, -0.09], 13);
```

`myDiv` will be a div in the DOM (webpage) that the component will use to render itself. Taking the above example:

``` HTML
<html>
  <head>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css">
    <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
  </head>
  <body>
    <div id="myDiv" style="width:100px; height:100px;">
  </body>
</html>
```
- Modify the component's default behaviour / extend component:  
  `.setView(...)` is a function to change some functionality of the component. In your case, you can write different functions that, for example, let the user define a `div` where the _Points Selector Tool_ is made available, or you can let the user add new models ( @hesamrabeti will explain the idea better ), aso.

**Comment by hesamrabeti** [comment]
We want to achieve the following goals with modularization:
- Organized, modular, and readable code. This is to allow for others to easily contribute to the project. 
- Allow for new external models to be integrated into the system easily, allowing for the recognition of different body parts and/or using new algorithms with different accuracy and performance profiles.

The reason for allowing external models is to allow others to easily develop models without having to host the UI components themselves. Also, allowing external models will allow users to easily try out different models. This would be especially interesting for researchers looking to benchmark different methods.

In order to achieve such a goal, we would have to implement layers of abstraction that separate computation and recognition from visualization. As an example, Bonestagram would execute a model which is fed with images from a web cam and outputs a set of vertices which is rendered by the visualization layer on top of the input image. This must be done in a manner which prevents malicious models from compromising the security of the application. For example, models can be executed in a Web Worker or an IFrame. A standardized communication protocol must be defined for setup and communication between the UI and the model. Modularization even allows for different models (e.g. hand + dental) to be executed at the same time.

This should be a stretch goal after we have implemented basic functionality.

**Comment by sacdallago** [comment]
Thinks to look at:
- http://browserify.org/
- https://github.com/webpack/webpack

**Comment by sacdallago** [comment]
When initializing bonestagram, it would be nice if the user could pass an object like:

``` javascript
var options = {
    videoClass: "myVideoClass",
    imgClass: "myImgClass"
}

bonestagram.init(options);
```

in your bonestagram init:

``` javascript
init: function(options){
   var videoClass =  options.videoClass || "bonestagram_video";
   var imgClass =  options.imgClass || "bonestagram_img";

   vid = document.getElementsByClassName(videoClass)[0];
   bonesImg = document.getElementById(imgClass);
....
```

Notice that the `||` in `var videoClass =  options.videoClass || "bonestagram_video";` means the following:
If `object.videoClass` is defined, use that value, otherwise use `"bonestagram_video"`, which by definition will be the default value.

This also means that if no object is passed to the initializer, the application will always use the default values :)

**Comment by fayeli** [comment]
Just updated that. Although I'm handling it a little bit differently so that it allows for user to select for the elements not through class name too, e.g.

```
var options = {
            video: $('#myVid'),
            img: $('#myImg')
        }
        bonestagram.init(options);
```

and in bonestagram init, I did

```
        init: function(options){
            if (typeof options !== "undefined") {
                vid = options.video[0];
                bonesImg = options.img[0];
            } else {
                vid = document.getElementsByClassName("bonestagram_video")[0];
                bonesImg = document.getElementsByClassName("bonestagram_img")[0];
            }
```

So essentially, we have the options to pass element references or to have bonestagram finding the default class names.

**Comment by sacdallago** [comment]
Be careful! You also need to check that each single value passed inside the object is defined, or else fallback on the default value!

In your `if .. else` statement you are only looking at if the options objects is defined, but someone might only pass one option, rather than all of them, eg:

```
options = {
  video: ...
}
```

In this case an error will rise, as `options.img`, and therefore also `bonesImg` won't be defined.

Secondly: I suppose the elements are singular in a page, meaning that there are no two `vid` elements. I therefore suggest you use HTML IDs rather than Classes and turn the `getElementsByClassName()` to `getElementById()`. This will also solve the not-too nice looking reference to the first element in the object list of the class search ( `...)[0];`);

Then: I like your idea, but you are mixing jQuery and native JavaScript element lookup here. Make sure this works 100%, otherwise I suggest you to give the user the possibility to pass the ID string identifier as an option, and not the reference to the HTML DOM element.

And lastly: Last semester I held a seminar about the introduction to JavaScript for students at our university. we recorded their presentations, which were about some topics that you might find interesting.

The two videos that you might find most interesting are:
1. [The module pattern and AMD](https://youtu.be/gBi-O2t-7fg), and
2. [Build tools, continuous integration and distribution](https://youtu.be/hPkXTq2TtSo?list=PLg46T0OlBIJ8AviPPZBXTB-TVusR3TuUf)

Only one part of the last video is interesting to you, so don't get scared by the length of it ;)

**Comment by fayeli** [comment]
Thanks for the good catch and links, Chris! (: I think I found your voice skipping through the video but I can be wrong though haha

Anyways, the main reason I didn't want to make it dependent on the ID is because I realised there can be only one ID per element. If the user were to use ID to identify the elements for other usage on their site, they won't be able to have Bonestagram functionality as well because the single ID is already taken.

Originally I was passing string for class or ID, but later I thought passing a reference to the DOM element allows for more flexibility. The user could select the right elements, through jQuery or native Javascript way as they wish, and still have Bonestagram features on the elements. 

But then, there are also some CSS that is needed and they are based on classes now... 

Should we actually allow that many options for the user?
